PYTHON_MYCMATH_SITE = $(PYTHON_MYCMATH_PKGDIR)src
PYTHON_MYCMATH_SITE_METHOD =  local
PYTHON_MYCMATH_SETUP_TYPE = setuptools

PYTHON_MYCMATH_HOST_PLATFORM = $(call qstrip,linux-$(BR2_ARCH))
PYTHON_MYCMATH_ENV += _PYTHON_HOST_PLATFORM=$(PYTHON_MYCMATH_HOST_PLATFORM)
$(eval $(python-package))
